import './globals.css';

import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import Footer from '@/components/Footer';
import Header from '@/components/Header';
import NextUIProvider from '@/providers/NextUIProvider';

const roboto = Roboto({
  subsets: ['latin'],
  weight: '400'
});

export const metadata: Metadata = {
  title: 'Arrow Consulting',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextUIProvider>
          <Header />
          <div>{children}</div>
          <Footer />
        </NextUIProvider>
      </body>
    </html>
  );
}
